"""add_user_profile_fields

Revision ID: 03de020e451c
Revises: 6e1cb08edd92
Create Date: 2026-03-22 13:26:18.642940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03de020e451c'
down_revision: Union[str, Sequence[str], None] = '6e1cb08edd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('cv_path', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_column('users', 'cv_path')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'school')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'user_code')
    # ### end Alembic commands ###
