"""after mear develop

Revision ID: 3e76b9074ab7
Revises: 12d327d61e10
Create Date: 2026-04-05 13:33:20.556717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e76b9074ab7'
down_revision: Union[str, Sequence[str], None] = '12d327d61e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # These legacy tables may already be removed by prior migrations.
    if inspector.has_table("kuppy_sessions"):
        op.drop_table("kuppy_sessions")
    if inspector.has_table("kuppy_participants"):
        op.drop_table("kuppy_participants")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kuppy_participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['kuppy_sessions.id'], name=op.f('kuppy_participants_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kuppy_participants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kuppy_participants_pkey'))
    )
    op.create_index(op.f('ix_kuppy_participants_id'), 'kuppy_participants', ['id'], unique=False)
    op.create_table('kuppy_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datetime_schedule', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('points_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('kuppy_sessions_host_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kuppy_sessions_pkey'))
    )
    op.create_index(op.f('ix_kuppy_sessions_id'), 'kuppy_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
