"""after mear develop

Revision ID: aee12f0ad8bc
Revises: 3e76b9074ab7
Create Date: 2026-04-05 13:39:02.824961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee12f0ad8bc'
down_revision: Union[str, Sequence[str], None] = '3e76b9074ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_sessions_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_time', sa.String(length=20), nullable=False),
    sa.Column('zoom_link', sa.String(length=1000), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('tags_csv', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_sessions_v2_creator_id'), 'professional_sessions_v2', ['creator_id'], unique=False)
    op.create_index(op.f('ix_professional_sessions_v2_id'), 'professional_sessions_v2', ['id'], unique=False)
    op.create_table('professional_session_registrations_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['professional_sessions_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_prof_session_student_v2')
    )
    op.create_index(op.f('ix_professional_session_registrations_v2_id'), 'professional_session_registrations_v2', ['id'], unique=False)
    op.create_index(op.f('ix_professional_session_registrations_v2_session_id'), 'professional_session_registrations_v2', ['session_id'], unique=False)
    op.create_index(op.f('ix_professional_session_registrations_v2_student_id'), 'professional_session_registrations_v2', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_session_registrations_v2_student_id'), table_name='professional_session_registrations_v2')
    op.drop_index(op.f('ix_professional_session_registrations_v2_session_id'), table_name='professional_session_registrations_v2')
    op.drop_index(op.f('ix_professional_session_registrations_v2_id'), table_name='professional_session_registrations_v2')
    op.drop_table('professional_session_registrations_v2')
    op.drop_index(op.f('ix_professional_sessions_v2_id'), table_name='professional_sessions_v2')
    op.drop_index(op.f('ix_professional_sessions_v2_creator_id'), table_name='professional_sessions_v2')
    op.drop_table('professional_sessions_v2')
    # ### end Alembic commands ###
